### ISSUE TITLE
Trying to run `git-sim add` with an empty repository (no commits yet) throws an error

### ISSUE THREAD

**Issue by Yamboy1** [initialcommit-com/git-sim#10]
Trying to use `git-sim add` on a newly created repository with no commits throws a git-sim error: "No commits in current Git repository". `git add` should not depend on any commits currently existing in the repository.

Btw, I love this project and am really excited to see where it will go in the future :)

**Comment by initialcommit-io** [comment]
Noted!!!  I'll look into this soon and get it fixed :D.  Thanks for the support! If you ever have any ideas/suggestions for the project please let me know!

**Comment by initialcommit-io** [comment]
Fixed in version 0.1.4, released.  You can update with `pip install git-sim --upgrade`.
