### ISSUE TITLE
Error in Dockerfile during 'apt update'

### ISSUE THREAD

**Issue by pjdurai** [initialcommit-com/git-sim#101]
Hi
I was trying to test git-sim in Mac OSX/Docker and ran into the following error during docker build.

ERROR [3/6] RUN apt update                                                                                                                                                 0.5s
------
[3/6] RUN apt update:
0.140
0.140 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
0.140
0.225 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
0.339 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
0.354 Err:1 http://deb.debian.org/debian bookworm InRelease
0.354   At least one invalid signature was encountered.
0.383 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
0.388 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
0.388   At least one invalid signature was encountered.
0.423 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
0.423   At least one invalid signature was encountered.
0.428 Reading package lists...
0.440 W: GPG error: http://deb.debian.org/debian bookworm InRelease: At least one invalid signature was encountered.
0.440 E: The repository 'http://deb.debian.org/debian bookworm InRelease' is not signed.
0.440 W: GPG error: http://deb.debian.org/debian bookworm-updates InRelease: At least one invalid signature was encountered.
0.440 E: The repository 'http://deb.debian.org/debian bookworm-updates InRelease' is not signed.
0.440 W: GPG error: http://deb.debian.org/debian-security bookworm-security InRelease: At least one invalid signature was encountered.
0.440 E: The repository 'http://deb.debian.org/debian-security bookworm-security InRelease' is not signed.
------
Dockerfile:5
--------------------
   3 |     WORKDIR /usr/src/git-sim
   4 |
   5 | >>> RUN apt update
   6 |
   7 |     RUN apt -y install build-essential python3-dev libcairo2-dev libpango1.0-dev ffmpeg
--------------------
ERROR: failed to solve: process "/bin/sh -c apt update" did not complete successfully: exit code: 100

Any Ideas?
Thanks

**Comment by initialcommit-io** [comment]
The dockerfile was created by a discussion in #50 contributed to by @Averagess. There was also discussion in #46 by @cvagner @borekb.

Sorry to ping you all out of nowhere - but any chance you can provide any input on the error above?

**Comment by initialcommit-io** [comment]
@pjdurai Hi again, and sorry looks like the authors of the dockerfile aren't available to assist with this one.

Were you ever able to get Git-Sim running on your end?
