### ISSUE TITLE
git-sim not recognized as command in M1 Apple

### ISSUE THREAD

**Issue by IsTheMartin** [initialcommit-com/git-sim#102]
Hey all 🖖 

I installed this git-sim in my m1 apple silicon by follwing [this guide](https://initialcommit.com/blog/git-sim#how-to-install-and-run-git-sim), however when I tried to execute `git-sim` in my terminal, that command does not exist `command not found: git-sim`

should I add it manually in `.zprofile`? or do I need to do something else?

Also, I read this other issue, but it is focused to windows os
- https://github.com/initialcommit-com/git-sim/issues/37

Thanks in advance

**Comment by initialcommit-io** [comment]
Hi @IsTheMartin !

Ahh, it might be related to using the Mac system python. If you look at the github Git-Sim page, specifically the "Quickstart" section (https://github.com/initialcommit-com/git-sim?tab=readme-ov-file#quickstart), you'll see it mentions a note for MacOS users:

> Note: For MacOS, it is recommended to NOT use the system Python to install Git-Sim, and instead use [Homebrew](https://brew.sh/) to install a version of Python to work with Git-Sim. Virtual environments should work too.

Please give this a try if you were previously trying to use the Mac system python to install and use Git-Sim.  (I'd recommend uninstalling git-sim from the system python / pip in the process).

Let me know if that works for you!

**Comment by initialcommit-io** [comment]
Hey there and happy new year.

Were you able to get this working?

**Comment by IsTheMartin** [comment]
Hey @initialcommit-io thank you, happy new year!

Yes, I was able to fix it by uninstalling python and installing again (by brew). 

Thank you for your help 🚀
