### ISSUE TITLE
TypeError: can only concatenate str (not "ManimColor") to str

### ISSUE THREAD

**Issue by DaniCPZ** [initialcommit-com/git-sim#104]
When trying to execute the `git-sim stash pop` command I get the following error in the console. 

TypeError: can only concatenate str (not "ManimColor") to str

- My operating system is Ubuntu 22.04
- git-sim version 0.3.3
- Manim Community v0.18.0

**Comment by initialcommit-io** [comment]
Hey there!

Sorry for the delay - when you submitted your issue I was pretty close to finishing up a new release (0.3.5) for git-sim, which I just released a few minutes ago!

There were several issues with the stash subcommands including "pop" and "apply".  I didn't encounter the specific error you mentioned, but can you try upgrading to the latest release and seeing if it fixes your issue?

To upgrade you can just run:  `pip3 install --upgrade git-sim`  (or `pip install --upgrade git-sim` depending on your local python configuration)

**Comment by initialcommit-io** [comment]
Hey @DaniCPZ ,

Just wanted to follow up on this!

**Comment by initialcommit-io** [comment]
Closing for now as I have not heard back.  Feel free to reopen any time!

**Comment by DaniCPZ** [comment]
After updating the error was solved, sorry for the delay in responding
