### ISSUE TITLE
How to run from source

### ISSUE THREAD

**Issue by ryanmcfall** [initialcommit-com/git-sim#24]
I want to play around with the source code a little bit, so I've cloned the repository locally.

What do I do in order to run my local version?  I don't see anything in `README.md` about this.

**Comment by initialcommit-io** [comment]
Please check the `CONTRIBUTING.md` file.

Closing this while you test, if you run into any issues feel free to reopen this.

**Comment by paketb0te** [comment]
Set up a virtual environment (e.g. `pip -m venv .venv` - this calls the module "venv" and creates a virtual environment in the directory `.venv`) and activate it (`source .venv/bin/activate` on Linux, see [DOCS](https://docs.python.org/3/library/venv.html) for other OSes).

Afterwards, you can run `pip install -e .` which will install everything in the current working directory into your virtual environment in editable mode (meaning you can work on your files and don't need to reinstall after every change).

**Comment by ryanmcfall** [comment]
In case someone comes across this issue, I can verify that the method suggested by @paketb0te works great.  Thanks for the suggestion - I like this better than editing out the prefix from the `import` statements as suggested in `CONTRIBUTING.md`.

**Comment by abhijitnathwani** [comment]
Thanks for confirming @ryanmcfall. The `contributing.md` is now updated to reflect these changes.

**Comment by initialcommit-io** [comment]
@ryanmcfall Yes thanks for testing the various options.  You're absolutely right changing the imports was not sustainable - it was just my hacky workaround.

We now have a much better option in the updated `CONTRIBUTING.md`.

Let us know if that works for you - it worked great for me even outside of a Virtualenv.
