### ISSUE TITLE
Error to execute git-sim command (windows 11)

### ISSUE THREAD

**Issue by Faridleo1998** [initialcommit-com/git-sim#28]
![image](https://user-images.githubusercontent.com/57077376/214892681-e2db3a97-bc92-4f93-9083-78ecd885fe64.png)

I have all installed dependencies:
![image](https://user-images.githubusercontent.com/57077376/214892960-c8a85a37-eed8-4d86-b1c4-cd443a6729e9.png)
![image](https://user-images.githubusercontent.com/57077376/214893021-9bf8822c-664f-43c2-9cfe-618aa85966af.png)

I execute `pip3 install git-sim` command and show me this (end lines):
![image](https://user-images.githubusercontent.com/57077376/214893453-b525be21-8f98-45d8-9062-8690d3b27d0b.png)

**Comment by initialcommit-io** [comment]
I'm not exactly sure why yet, but sometimes when installing on Windows the path to the git-sim executable does not get set during installation.

For now, the solution is to run a search for the executable `git-sim.exe` and add it to your PATH environment variable. Then close out of your command prompt and open a new one.

Please give that a try and let me know if it works for you.

**Comment by initialcommit-io** [comment]
@Faridleo1998 see above.

**Comment by Faridleo1998** [comment]
Where I found the git-sim.exe file? I search git-sim.exe term on my computer but it is show nothing :(

**Comment by initialcommit-io** [comment]
Can you try this and see if you can find the path to the `git-sim.exe` file?

1) Open command prompt as administrator
2) Run: `dir "\git-sim.exe" /s`

That should give you the path to the executable which you can then add to your PATH environment variable.

Let me know if it works!

**Comment by Faridleo1998** [comment]
Sorry, I installed git-sim with powershell and it is not create the git-sim.exe. After, I executed the same command but command prompt and works! Thank you for you help  :D

**Comment by initialcommit-io** [comment]
No worries, glad you got it working!  Please let me know if you have any suggestions or run into issues using the tool!
