### ISSUE TITLE
No module named git-sim

### ISSUE THREAD

**Issue by mlaurentec** [initialcommit-com/git-sim#29]
I install all the depencies , and i want to execute the command **git-sim  -h**  I get the following Error: **No module named git-sim**.

**Comment by initialcommit-io** [comment]
Hi @mlaurentec,

Are you able to run any of the other Git_sim commands, like `git-sim log`?

Please provide the following info:
-Full error message
-OS you are on
-Python version and whether you're in virtual environment
-Git-Sim version
-Installation steps that you used

**Comment by mlaurentec** [comment]
Hello @initialcommit-io , thanks for answering. 
The full error is:
![image](https://user-images.githubusercontent.com/65027652/214952311-fe570f5d-dc30-4e62-9d0b-1d424097cdd4.png)

this is the git-sim version:
Version: 0.1.5
![image](https://user-images.githubusercontent.com/65027652/214952079-fb05268a-e68b-40c7-a906-0833c03bcb67.png)

OS: Windows 10

Python version: 3.9.13 
- im not using a virtual enviroment

The instalation steps were
- Install [Manim and Manim dependencies](https://www.manim.community/) for your OS
in my case windows 10 i execute the following comand
`choco install manimce`
- Install git-sim: $ pip3 install git-sim

**Comment by initialcommit-io** [comment]
@mlaurentec Can you try this and see if you can find the path to the `git-sim.exe` file and add it to your PATH environment variable?

1) Open command prompt as administrator
2) Run: dir "\git-sim.exe" /s
3) That should give you the path to the executable which you can then add to your PATH environment variable.

Let me know if it works!

**Comment by mlaurentec** [comment]
@initialcommit-io , after following the steps you indicated, it worked correctly 👍.
Thank you very much for your time and great help.
By the way, I've been testing the library and it's very useful.
