### ISSUE TITLE
Tilde expansion not supported

### ISSUE THREAD

**Issue by anothermh** [initialcommit-com/git-sim#3]
[Tilde expansion](https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html) is not supported. For example, consider the following command:

```shell
git-sim --media-dir=~/temp log
```

The expectation is that `media-dir` will map to `$HOME/temp`, for example `/Users/foo/temp`. Instead it maps to the current directory and creates a sub-directory with the literal name `~`, e.g. `./~/temp`:

```shell
└── ~
    └── temp
        └── git-sim_media
            ├── images
            ├── texts
            └── videos
                └── 1080p60
                    └── partial_movie_files
                        └── GitSim
```

This was tested on macOS using both ZSH and fish for the shell, using python 3.11.1.

The problem appears to be here:

https://github.com/initialcommit-com/git-sim/blob/c2effc266970bc4be373f1868fec8beb9ee885ed/git_sim/__main__.py#L79

Using [`os.path.expanduser`](https://stackoverflow.com/a/2057072/3784008) will allow tilde expansion.

**Comment by initialcommit-io** [comment]
Lol whoops, good catch.  Thanks for finding the exact location in the codebase and suggesting a solution!  Any chance you want to submit a pull request for it? :D
