### ISSUE TITLE
git-sim is not recognized as an internal or external command

### ISSUE THREAD

**Issue by benswedlove** [initialcommit-com/git-sim#37]
Even after following installation directions and restart computer I cannot use git-sim.

**Comment by initialcommit-io** [comment]
If you're on Windows can you try this and see if you can find the path to the git-sim.exe file?

1) Open command prompt as administrator
2) Run: dir "\git-sim.exe" /s
3) That should give you the path to the executable which you can then add to your PATH environment variable.

Let me know if it works!

If you're not on Windows, please let me know what OS you're on and exactly what steps you ran to install it.

**Comment by benswedlove** [comment]
Hi thanks!
Found it here:
C:\Users\*user*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts

I think this got installed using the VS code Python extension's python package instead of the regular one.
After installing Python 3.11 and making sure to install using PIP from the new install everything works!

These steps should help anyone in the future"
1) Install Python to c:\Python311\
2) Open cmd window
3) run "cd C:\Python311\Scripts\"
4) run:  ".\pip.exe install git-sim"
5) cd to a folder that has a git repo, then run "git-sim status" or "C:\Python311\Scripts\git-sim.exe status"

**Comment by initialcommit-io** [comment]
Glad you got it working @benswedlove , and thanks for posting the steps that fixed it for you!
