### ISSUE TITLE
If there are branches whose names include slash(/) in local, KeyError will occur on any operations.

### ISSUE THREAD

**Issue by k1997y** [initialcommit-com/git-sim#41]
A git branch name can include slash symbol(/).   
e.g) feature/feature-A  

However, `git-sim` throws `KeyError`  if the branches's name include slash.
There is the reason most likely in following lines.  
https://github.com/initialcommit-com/git-sim/blob/84811ee2523067296a4c7115506e10e713e9f8f0/git_sim/git_sim_base_command.py#L319-L327

This if-statement conditional branch is insufficient.  
If possible, could you consider other means of determining whether a branch is a remote branch or not?
I also try to explore the way. (I am not familiar with Python and Git, so it is perhaps difficult for me to make Pull Request about this issue.)

**Comment by initialcommit-io** [comment]
@k1997y Yes you're right.  I will use the supported GitPython calls to determine if the branch is local or remote, instead of this slash test.  I will push a fix for this soon.  Thanks for finding and reporting this bug!

**Comment by initialcommit-io** [comment]
@k1997y Just pushed a fix for this in new version 0.1.8.  Please update using:

```
$ pip install git-sim --upgrade
```

And let me know if it works now!  I will close this for now but feel free to reopen if any issues.

**Comment by k1997y** [comment]
@initialcommit-io 
Thank you for your very quick response and fixing!!
I expect you to make this product better, Thank you very much.
