### ISSUE TITLE
Feature request: support ```git cherry-pick -e```

### ISSUE THREAD

**Issue by senali-d** [initialcommit-com/git-sim#47]
Currently cherry-pick is only supported for the following command.
```git cherry-pick```

```git cherry-pick -e <message>``` command not supported.

So, I'm suggest the above mention command as a new feature.

**Comment by initialcommit-io** [comment]
Just added this in version 0.2.2!  Note that git-sim doesn't support opening the default text editor to edit the commit message the way Git does, so the way you'll need to run this command is `git-sim cherry-pick <commit> -e "Updated commit message"`

To update to the latest version of git-sim, run:

```
$ pip install git-sim --upgrade
```

Closing for now, but feel free to add comments or reopen if you run into any issues!
