### ISSUE TITLE
Optimize column spacing and file path length for improved display

### ISSUE THREAD

**Issue by eltoncezar** [initialcommit-com/git-sim#48]
I can't reopen the previous issue, so I'm opening a new one :smile: 

              Thanks for the quick fix! Now it looks like this:
![image](https://user-images.githubusercontent.com/2071672/215557244-0ab0f3a5-3f70-4019-b2fe-a2be24950e4a.png)

Much more manageable. But... I think it should use all the available space if possible. What do you think about it?

_Originally posted by @eltoncezar in https://github.com/initialcommit-com/git-sim/issues/25#issuecomment-1409079159_

**Comment by initialcommit-io** [comment]
@eltoncezar Let me play around with it and I'll let you know.

**Comment by initialcommit-io** [comment]
@eltoncezar This will be improved in the next release.

**Comment by initialcommit-io** [comment]
@eltoncezar This feature enhancement was just released in v0.2.3. Upgrade with `$ pip install git-sim --upgrade` and feel free to reopen this ticket if any issues or questions.
