### ISSUE TITLE
how to setup via brew in mac

### ISSUE THREAD

**Issue by wajidp** [initialcommit-com/git-sim#5]
how do i install with `homebrew` in mac os ?

**Comment by PaulisMatrix** [comment]
@wajidp, You need to install ffmpeg and manim which are its dependencies. 

Check here: https://initialcommit.com/blog/git-sim#how-to-install-and-run-git-sim

**Comment by initialcommit-io** [comment]
Yes @wajidp please follow the steps at the link in the previous comment.  Go to the link in step (1) on the Manim website it will tell you how to install Manim for MacOS.

Then you can use Homebrew to install a version of Python newer than 3.7, and then use pip to install git-sim.  Please test it out and let us know if any issues.

**Comment by wajidp** [comment]
ok thanks @initialcommit-io @PaulisMatrix
