### ISSUE TITLE
Add global option --stdout to write raw image data to stdout for redirection into other programs

### ISSUE THREAD

**Issue by borekb** [initialcommit-com/git-sim#56]
Would you consider adding an option like `--stdout` which would write the image data directly to stdout so that it can be displayed directly by imgcat, w3m or viu?

**Comment by initialcommit-io** [comment]
@borekb Yup, this will be included in the next release 😉

**Comment by initialcommit-io** [comment]
@borekb This feature was just released in v0.2.3. Upgrade with `$ pip install git-sim --upgrade` and feel free to reopen if any issues or questions.
