### ISSUE TITLE
Very slow on M1 mac

### ISSUE THREAD

**Issue by Coder2012** [initialcommit-com/git-sim#57]
I had no problem getting everything installed in a `venv` now running python 3.10.9 but it just hangs for minutes and just says simulating and sometimes will eventually generate an image.

Any ideas how to debug this issue?

**Comment by Coder2012** [comment]
closing issue, after a restart its fine

**Comment by initialcommit-io** [comment]
@Coder2012 Glad you got it working!  I'm on an Intel Mac and I have noticed that on the first run it can be a bit slow, but it never took *minutes* to run...  Anyway, glad a restart took care of it!

**Comment by initialcommit-io** [comment]
@Coder2012 If you have any issues with git-sim or suggestions for improvements please let us know.
