### ISSUE TITLE
Git-sim hangs with GLib-GIO-WARNING

### ISSUE THREAD

**Issue by bradykelly** [initialcommit-com/git-sim#58]
I have just installed git-sim v0.2.3 on Windows 10 v10.0.19044 via `pip3 install git-sim` after installing Manim with `choco install manimce`. Chocolatey installed the following packages:

>  - manimce v0.17.2
>  - python v3.10.8
>  - python3 v3.10.8
>  - ffmpeg v5.1.2
>  - vcredist2015 v14.0.24215.20170201

For python3 Chocolatey output the following log entries:

> Installing 64-bit python3...
> python3 has been installed.
> WARNING: Provided python InstallDir was ignored by the python installer
> WARNING: Its probable that you had pre-existing python installation
> WARNING: Python installed to: 'C:\Program Files\Python310'
> WARNING: Installation folder is not the default. Not changing permissions. Please ensure your installation is secure.

For python Chocolatey output these log entries:

> Found Python 3.10 from Registry
> Found Install Path - C:\Program Files\Python310\python.exe
> Found python at 'C:\Program Files\Python310\python.exe' using it.
> Using python version Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]

When I run `git-sim log` the following text is output and git-sim seems to hang. I.e. nothing happens for several minutes.

> Simulating: git log
 (process:2796): GLib-GIO-WARNING **: 22:04:04.968: Unexpectedly, UWP app `50582LuanNguyen.NuGetPackageExplorer_6.0.64.0_x64__w6y2tyx5bpzwa' (AUMId `50582LuanNguyen.NuGetPackageExplorer_w6y2tyx5bpzwa!App') supports 3 extensions but has no verbs
 
 After a few minutes I hit Ctrl+C and git-sim output `Aborted.` to the terminal and then exited.
 
 After aborting the following directories were created:
 

> git-sim_media\Apps.Bison\images
> git-sim_media\Apps.Bison\texts
> git-sim_media\Apps.Bison\videos

I ran git-sim from the directory `\Dev\Apps.Bison\GlobalPlatform\PlatformAddins\GlobalPlatformAddin`. The images and videos directories are empty but the texts directory contains 10 .svg files.

**Comment by initialcommit-io** [comment]
@bradykelly Thanks for dropping the details here. Sometimes the first run after install takes a bit, but shouldn't take that long.  Then subsequent runs after been fast for me.  Can you try these steps and let me know the result:

1) Try just running `git-sim -h` and let me know if it hangs or prints the help
2) Try running `git-sim -d log`, the -d flag will prevent it from trying to open the image file immediately, which can sometimes lead to the Glib warnings...
3) Try running `git-sim log` again and just let it run for like 10 mins to see if it's just running super slow or actually hanging
4) Restart your machine and try again (surprisingly this actually worked for someone having a similar issue on MacOS

Once you can get it to run for the first time it's usually much faster after that.

Thanks for your patience!

**Comment by bradykelly** [comment]
Thank you very much. I was just a bit too hasty the last time I tried it, but when I tried now I went away and did something else and it worked fine. I don't even think it took 10 minutes. Just BTW, I got the warning even just running `git-sim -h`
