### ISSUE TITLE
Feature Request - Chaining multiple commands in series

### ISSUE THREAD

**Issue by jygastaud** [initialcommit-com/git-sim#59]
Hi,

Thanks for the time you invest in that project. It will help a lot to explain concept.

What could be really cool would be to be able to chain many command and display an image with all those steps and not each step in individual image.

"Basic exemple" would be to have `checkout` a new branch, `add`, `commit` + merge in previous branch in the same image.

**Comment by paketb0te** [comment]
Not a bad idea IMO, but I am not sure how we can build that - somehow we'd need to know whether a "word" is an argument to a previous command, or if it is already the next command to execute :thinking: 

To illustrate:

```sh
git_sim add foo.py commit stash pop
```

It might be kinda easy to figure out that `foo.py` is a file name (but what about files without extension?) and not a command, but how would we know if `pop` is a subcommand of `stash`, or a command on it's own?

I _guess_ this might be doable by comparing each word to all command names and comparing it to "where in the command/subcommand tree are we right now?", but to me it looks not trivial to implement.

**Comment by paketb0te** [comment]
The simple case where each command takes no arguments is actually surprisingly simple, but of course it does not help with the previously mentioned problem...

```py
import typer

app = typer.Typer()


@app.command(name="bar")
def bar():
    print("bar")


@app.command(name="baz")
def baz():
    print("baz")


@app.command(name="multi")
def multi(cmds: list[str]):
    registered_func_names = [reg_cmd.name for reg_cmd in app.registered_commands]
    for cmd in cmds:
        if cmd in registered_func_names:
            func = globals()[cmd]
            func()
        else:
            print(f"'{cmd}' is not a valid command, skipping...")


if __name__ == "__main__":
    app()
```

**Comment by jygastaud** [comment]
> Not a bad idea IMO, but I am not sure how we can build that - somehow we'd need to know whether a "word" is an argument to a previous command, or if it is already the next command to execute thinking

I can imagine at least 3 different ways to handle that :
1. Force seperator and/or quote each git command inside your line
    You exemple will become
    ```
    git_sim "add foo.py" "commit" "stash" "pop"
    ```
1. Ready a file that contain 1 command per line and just iterate over the file (sounds the easiest way for me)
1. make git-sim "interactive" so you can run `git-sim -i` then enter a command, press enter, an other command, press enter…  
That is easy for small workflow but not that good from a UX perspective

**Comment by initialcommit-io** [comment]
@jygastaud Interesting thought!  We might consider this in the future but for now, we have to focus on getting full coverage of the most common Git commands before we think about chaining together into a larger workflow. Closing for now.

**Comment by Shahar-do** [comment]
Just started using git-sim few days ago and thought exactly the same.
So just wanted to say that the idea of chaining multiple commands sounds awesome to me and for me personally that would be extremely helpful.
I guess some kind of strategy to tackle the above mentioned issue regarding of separating commands, words, and arguments,
is simply requesting the user to create a file in which each command is in a separate line.
One other strategy, is using any special character to separate between commands (quotation marks would clearly be most intuitive but I aint sure that's gonna work)
