### ISSUE TITLE
Add -v, --version flag to display program version info

### ISSUE THREAD

**Issue by initialcommit-io** [initialcommit-com/git-sim#81]
Hi @paketb0te ,

I tried implementing `git-sim -v` and `git-sim --version` options a few weeks ago but had some trouble due to not being super familiar with Pydantic/Typer.  I thought this one might be right up your alley to take a crack at 😄 

Let me know!

**Comment by paketb0te** [comment]
@initialcommit-io yeah good idea, let me give it a go!

**Comment by initialcommit-io** [comment]
@paketb0te Thank you!!! Just tested and works for me 🥳
